-- location
INSERT INTO location(id, dest, address, member) VALUES('1', '淡島ホテル(ショップしまたろうにて販売)', '沼津市内浦重寺186', '鞠莉');
INSERT INTO location(id, dest, address, member) VALUES('2', 'オーシャンビューフジミ', '沼津市西浦江梨993', '果南');
INSERT INTO location(id, dest, address, member) VALUES('3', 'SUNSUN!サンシャインカフェ', '沼津市大手町3-1-1', 'ダイヤ');
INSERT INTO location(id, dest, address, member) VALUES('4', '松月', '沼津市内浦88-36', '花丸');
INSERT INTO location(id, dest, address, member) VALUES('5', '三ノ浦総合案内所', '沼津市内浦長浜83-124', 'ルビィ');
INSERT INTO location(id, dest, address, member) VALUES('6', 'ゲーマーズ沼津店', '沼津市添地町72青秀ビル1階', '善子');
INSERT INTO location(id, dest, address, member) VALUES('7', '伊豆・三津シーパラダイス', '沼津市内浦長浜3-1', '曜');
INSERT INTO location(id, dest, address, member) VALUES('8', '千鳥観光汽船', '沼津市内浦三津43-7', '梨子');
INSERT INTO location(id, dest, address, member) VALUES('9', '安田屋旅館', '沼津市内浦三津19', '千歌');
INSERT INTO location(id, dest, address, member) VALUES('10', '浦の星女学院キッチンカー', ' キッチンカー店頭にて', '曜');
INSERT INTO location(id, dest, address, member) VALUES('11', '浜忠', '沼津市上土町80', 'ルビィ');
INSERT INTO location(id, dest, address, member) VALUES('12', '浜の家', '沼津市内浦三津42-3', '鞠莉');
INSERT INTO location(id, dest, address, member) VALUES('13', 'マルサン書店 仲見世店', '沼津市大手町5-3-13', '花丸');
INSERT INTO location(id, dest, address, member) VALUES('14', 'つじ写真館', '沼津市上土町36', '善子');
INSERT INTO location(id, dest, address, member) VALUES('15', '仲見世商店街(マルサン書店仲見世店にて販売)', '沼津市大手町5-3-13', '曜');
INSERT INTO location(id, dest, address, member) VALUES('16', '市川', '沼津市上土町100-1', 'ダイヤ');
INSERT INTO location(id, dest, address, member) VALUES('17', 'あわしまマリンパーク(ショップしまたろうにて販売)', '沼津市内浦重寺186', '果南');
INSERT INTO location(id, dest, address, member) VALUES('18', 'モスバーガー富士急沼津店', '沼津市大手町3丁目2-1', '梨子');
INSERT INTO location(id, dest, address, member) VALUES('19', 'JAなんすん(みなと新鮮館)', '沼津市千本港町128-1', '千歌');
INSERT INTO location(id, dest, address, member) VALUES('20', '内浦漁業直営 いけすや', '沼津市内浦小海30-103 ', 'ダイヤ');
INSERT INTO location(id, dest, address, member) VALUES('21', '伊豆箱根鉄道 伊豆長岡駅', '伊豆の国市南条773-2', '果南');
INSERT INTO location(id, dest, address, member) VALUES('22', '欧蘭陀館', '沼津市下河原町1146-33', '曜');
INSERT INTO location(id, dest, address, member) VALUES('23', 'びゅうお', '沼津市千本港町117', '鞠莉');
INSERT INTO location(id, dest, address, member) VALUES('24', 'グランマ', '沼津市上土町63', '善子');
INSERT INTO location(id, dest, address, member) VALUES('25', '大瀬館', '沼津市西浦江梨325-1', 'ルビィ');
INSERT INTO location(id, dest, address, member) VALUES('26', '東海バスオレンジシャトル ※東海バストラベル沼津駅前案内所', '沼津市大手町1-1-1', '千歌');
INSERT INTO location(id, dest, address, member) VALUES('27', '駿陽荘 やま弥', '沼津市西浦平沢92-4', '花丸');
INSERT INTO location(id, dest, address, member) VALUES('28', 'セブンイレブン 伊豆・三津シーパラダイス前店', '沼津市内浦三津46', '梨子');
INSERT INTO location(id, dest, address, member) VALUES('29', 'うおがし寿司 イーラde店', '沼津市大手町1-1-6 イーラde 3F', 'ルビィ');
INSERT INTO location(id, dest, address, member) VALUES('30', 'マルサンホビー', '沼津市上土町66', '鞠莉');
INSERT INTO location(id, dest, address, member) VALUES('31', '沼津港 魚永', '沼津市千本港町109', '花丸');
INSERT INTO location(id, dest, address, member) VALUES('32', 'HAMBURGER&CAFE 沼津バーガー', '沼津市千本港町83-1', '善子');
INSERT INTO location(id, dest, address, member) VALUES('33', 'アントレ', '沼津市大手町1-1-1', '曜');
INSERT INTO location(id, dest, address, member) VALUES('34', 'ほさか', '沼津市大手町5-2-9', 'ダイヤ');
INSERT INTO location(id, dest, address, member) VALUES('35', 'すしの磯丸 沼津みなと店', '沼津市千本港町97', '果南');
INSERT INTO location(id, dest, address, member) VALUES('36', 'イシバシプラザ', '沼津市高島本町1-5', '梨子');
INSERT INTO location(id, dest, address, member) VALUES('37', 'マルカ', '沼津市内浦重須305-8', '千歌');
INSERT INTO location(id, dest, address, member) VALUES('38', 'ふみ野', '沼津市千本港町109 ダイレイビル1F', 'ダイヤ');
INSERT INTO location(id, dest, address, member) VALUES('39', '食堂・ひもの販売 あじや', '沼津市千本港町128-1 沼津みなと新鮮館内', '鞠莉');
INSERT INTO location(id, dest, address, member) VALUES('40', 'ファミリーマート沼津下香貫店', '沼津市下香貫2973-6', '果南');
INSERT INTO location(id, dest, address, member) VALUES('41', '阿見屋パーキング', '沼津市上土町1-1', '千歌');
INSERT INTO location(id, dest, address, member) VALUES('42', 'マルキュウ魚健', '沼津市千本港町124', '曜');
INSERT INTO location(id, dest, address, member) VALUES('43', '大黒屋', '沼津市町方町71', '花丸');
INSERT INTO location(id, dest, address, member) VALUES('44', '布澤呉服店', '沼津市上土町100-1', '梨子');
INSERT INTO location(id, dest, address, member) VALUES('45', '沼津アーケード名店街', '沼津市町方町111', 'ルビィ');
INSERT INTO location(id, dest, address, member) VALUES('46', 'TONYS HONOLULU', '沼津市千本港町128-3 沼津魚市場INO 2F', '善子');
INSERT INTO location(id, dest, address, member) VALUES('47', '海のステージ。', '沼津市西浦木負768-9', '曜');
INSERT INTO location(id, dest, address, member) VALUES('48', 'OH!MOS(農業組合法人おもす)', '沼津市内浦重須14-10', '花丸');
INSERT INTO location(id, dest, address, member) VALUES('49', 'とさわや', '沼津市内浦三津88-15', '善子');
INSERT INTO location(id, dest, address, member) VALUES('50', '海鮮丼と魚河岸定食 かもめ丸', '沼津市千本港町101 千本一ビル1階', 'ダイヤ');
INSERT INTO location(id, dest, address, member) VALUES('51', '赤から 沼津店', '沼津市米山町1-5', 'ルビィ');
INSERT INTO location(id, dest, address, member) VALUES('52', '辻宗商店', '沼津市内浦三津538', '花丸');
INSERT INTO location(id, dest, address, member) VALUES('53', 'ロットン', '沼津市上土町10', '梨子');
INSERT INTO location(id, dest, address, member) VALUES('54', 'リヴァージュ洋菓子店', '沼津市下香貫柿原2885-2', '千歌');
INSERT INTO location(id, dest, address, member) VALUES('55', '総合事務用品フヂイ', '沼津市通横町6', '善子');
INSERT INTO location(id, dest, address, member) VALUES('56', 'アベリー', '沼津市市場町3-20 三和生興ビル2F リカビリーエンジェル内', '善子');
INSERT INTO location(id, dest, address, member) VALUES('57', 'アキシン商店', '沼津市内浦重寺45', '鞠莉');
INSERT INTO location(id, dest, address, member) VALUES('58', '沼津グランドホテル', '沼津市大手町3丁目6-12', '千歌');
INSERT INTO location(id, dest, address, member) VALUES('59', 'アニメイト 沼津店', '沼津市大手町5-9-21 マルトモビル1F', '曜');
INSERT INTO location(id, dest, address, member) VALUES('60', 'マルニ茶業 沼津みなと新鮮館', '沼津市千本港町128-1 沼津みなと新鮮館内', '花丸');
INSERT INTO location(id, dest, address, member) VALUES('61', '沼津・湯河原温泉 万葉の湯', '沼津市岡宮1208-1', '果南');
INSERT INTO location(id, dest, address, member) VALUES('62', 'おさかな食堂やまや', '沼津市内浦三津199-4', 'ルビィ');
INSERT INTO location(id, dest, address, member) VALUES('63', '沼津リバーサイドホテル', '沼津市上土町100-1', '善子');
INSERT INTO location(id, dest, address, member) VALUES('64', '松浦酒店', '沼津市大手町3-9-1', '果南');
INSERT INTO location(id, dest, address, member) VALUES('65', '大田呉服店', '沼津市高島町3-3', '梨子');
INSERT INTO location(id, dest, address, member) VALUES('66', '旅館はまゆう荘', '沼津市西浦江梨986', 'ダイヤ');
INSERT INTO location(id, dest, address, member) VALUES('67', '赤池カーコミュニケーツシステムズ', '沼津市旭町19', '鞠莉');
INSERT INTO location(id, dest, address, member) VALUES('68', '遠藤新聞舗', '沼津市大手町5-11-3 4階', '曜');
INSERT INTO location(id, dest, address, member) VALUES('69', '漁師寿し 網元武田丸', '沼津市千本港町115-4', '花丸');
INSERT INTO location(id, dest, address, member) VALUES('70', 'ブルーウォーター', '沼津市魚町15', '千歌');
INSERT INTO location(id, dest, address, member) VALUES('71', 'くるら戸田', '沼津市戸田1294-3', '鞠莉');
INSERT INTO location(id, dest, address, member) VALUES('72', '杉長水産', '沼津市千本中町35', 'ルビィ');
INSERT INTO location(id, dest, address, member) VALUES('73', '木村屋', '沼津市千本港町115-4', '梨子');
INSERT INTO location(id, dest, address, member) VALUES('74', '沼津ラクーン', '沼津市大手町3-4-1 5階 『カラオケCLUB DAM』横スペース', '千歌');
INSERT INTO location(id, dest, address, member) VALUES('75', '鮨庵さいとう みなと旬彩街店', '沼津市千本港町115-4', '曜');
INSERT INTO location(id, dest, address, member) VALUES('76', 'coffee桜', '沼津市千本緑町1-1', '梨子');
INSERT INTO location(id, dest, address, member) VALUES('77', '千鳥ひものセンター', '沼津市千本港町128', 'しいたけ');
INSERT INTO location(id, dest, address, member) VALUES('78', 'THE 3RD PLANET BiVi沼津店', '沼津市大手町1-1-5 BiVi3階', '果南');
INSERT INTO location(id, dest, address, member) VALUES('79', 'CBカレーキッチン', '沼津市下香貫藤井原1653-1', '花丸');
INSERT INTO location(id, dest, address, member) VALUES('80', '内浦漁業協同組合', '沼津市内浦小海30-103 ※内浦漁業直営 いけすや内', '曜');
INSERT INTO location(id, dest, address, member) VALUES('81', 'ホテル沼津キャッスル', '沼津市日の出町1-1', '善子');
INSERT INTO location(id, dest, address, member) VALUES('82', '沼津御用邸記念公園', '沼津市下香貫島郷2802-1', 'ダイヤ');
INSERT INTO location(id, dest, address, member) VALUES('83', 'しーらかんすCaf?', '沼津市上香貫三園町1381-3', 'ルビィ');
INSERT INTO location(id, dest, address, member) VALUES('84', '石田茶業 北口支店', '沼津市高島町12-5', '鞠莉');
INSERT INTO location(id, dest, address, member) VALUES('85', 'カラオケ ラジオシティ 沼津駅北店', '沼津市米山町1-5', 'ダイヤ');
INSERT INTO location(id, dest, address, member) VALUES('86', 'サスナカ長澤水産', '沼津市獅子浜92 ', '果南');
INSERT INTO location(id, dest, address, member) VALUES('87', '増米', '沼津市獅子浜22-18', '千歌');
INSERT INTO location(id, dest, address, member) VALUES('88', 'ダイワロイネットホテルぬまづ', '沼津市大手町1-1-4', '善子');
