-- location 2019/09/14 追加分 TODO:公式情報を反映
--INSERT INTO location(id, dest, address, member) VALUES
--    ('1', '淡島ホテル(ショップしまたろうにて販売)', '沼津市内浦重寺186', '鞠莉');
--    ,('2', 'オーシャンビューフジミ', '沼津市西浦江梨993', '果南');